### ISSUE TITLE
Re-implement all discord messages templates to be ts models and files

### ISSUE THREAD

**Issue by 54UL** [cBotFoundation/cBot.ts#7]
translate and implement these message templates into typescript.
https://github.com/54UL/dBot/tree/main/services/implementations/discord-messages-templates

Factorize and generate the next templates
- [x]  CustomizableReply (title, custom content, buttons, etc)
- [x]  PromptReply (title,content,yes/no buttons)
- [x]  Theme

note: current implementation is not factorized and can be shrink into the concepts above (build the current ones on top of this as example)

**Comment by EdgarMtz00** [comment]
#33 Solves the task on this issue, but further extension of this will be required in the future
